interface LeagueInfo {
  readonly copyright: string,
  leagues: Array<{
    id: number,
    name: string,
    link: string,
    abbreviation: string,
    nameShort: string,
    seasonState: string,
    hasWildCard: boolean,
    hasSplitSeason: boolean,
    numGames: number,
    hasPlayoffPoints: boolean,
    numTeams: number,
    numWildcardTeams: number,
    seasonDateInfo: {
      seasonId: string,
      preSeasonStartDate: string,
      preSeasonEndDate: string,
      seasonStartDate: string,
      springStartDate: string,
      springEndDate: string,
      regularSeasonStartDate: string,
      lastDate1stHalf: string,
      allStarDate: string,
      firstDate2ndHalf: string,
      regularSeasonEndDate: string,
      postSeasonStartDate: string,
      postSeasonEndDate: string,
      seasonEndDate: string,
      offseasonStartDate: string,
      offSeasonEndDate: string,
      seasonLevelGamedayType: string,
      gameLevelGamedayType: string,
      qualifierPlateAppearances: number,
      qualifierOutsPitched: string,
    },
    season: string,
    orgCode: string,
    conferencesInUse: boolean,
    divisionsInUse: boolean,
    sport: {
      id: number,
      link: string
    },
    sortOrder: number,
    active: boolean
  }>,
}

export default LeagueInfo